version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src     # live-reload de React
      - ./frontend/public:/app/public # archivos públicos
      - /app/node_modules           # preservar node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/src:/app/src           # live-reload, nodemon
      - /app/node_modules            # preservar node_modules
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: ejemplo
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "5432:5432"  # expuesto en dev para inspección
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
  